# Generated by Django 3.2.24 on 2024-02-13 06:46

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
                ('duration', models.CharField(default='3 days', max_length=50)),
                ('start_place', models.CharField(default='Kabul', max_length=50)),
                ('end_place', models.CharField(default='Bamyan', max_length=50)),
                ('group_size', models.IntegerField(choices=[(4, 'Four'), (8, 'Eight'), (12, 'Tweleve'), (16, 'Sixteen')], default=4)),
                ('description', models.TextField(default='No description is provided!')),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start', models.CharField(max_length=15)),
                ('end', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TourAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, help_text='Warning editing thisfield will change the About Us section on the home page!')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bamyan.package')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='bamyan.season'),
        ),
    ]
